name: cs492_weather_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  geolocator: ^11.0.0
  geocoding: ^2.1.1
  http: ^1.2.0
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  provider: ^6.1.2
  dots_indicator: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/sql/create.sql
    - assets/sql/insert.sql
    - assets/sql/get_all.sql
    - assets/sql/delete.sql
