name: cs492_weather_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  http: ^1.2.0
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  provider: ^6.1.2
  google_fonts: ^6.2.0
  shimmer: ^3.0.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    # sql
    - assets/sql/create.sql
    - assets/sql/insert.sql
    - assets/sql/get_all.sql
    - assets/sql/delete.sql
    # images
    - assets/images/confused.png
    - assets/images/weather/

flutter_launcher_icons:
  android: true
  image_path: "assets/images/logo.jpeg"
  adaptive_icon_background: "#0bb584"
  adaptive_icon_foreground: "assets/images/logo.jpeg"
